# Generated by Django 4.2.6 on 2023-10-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_apply_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cv',
            field=models.FileField(default='', upload_to='applies/'),
            preserve_default=False,
        ),
    ]
