# Generated by Django 4.2.6 on 2024-12-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0016_alter_job_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
